/* DDL */
-- BOARD
CREATE TABLE `TBL_BOARD` (
	`BOARD_NO` INT NOT NULL AUTO_INCREMENT COMMENT '글 번호',
	`BOARD_TITLE` VARCHAR(300) NULL COMMENT '글 제목',
	`BOARD_CONTENT` TEXT NULL COMMENT '글 내용',
	`DEL_YN` VARCHAR(1) NULL DEFAULT 'N' COMMENT '삭제여부(Y/N)',
	`REG_NO` INT NULL COMMENT '작성자',
	`REG_DTTM` VARCHAR(14) NULL COMMENT '작성일시',
	PRIMARY KEY (`BOARD_NO`)
)
COMMENT='게시판';

/* DML */